### ISSUE TITLE
Windows - Open 2 kiosk browsers

### ISSUE THREAD

**Issue by bboerendans** [grafana/grafana-kiosk#108]
I'm trying to open 2 Chrome browsers (2 different urls) in kiosk mode since we have dual monitors on 1 computer. I can't get it working correctly.

I'm using a config file (based on the example), which is working fine for 1 monitor. 
CMD file content: 

```cmd
grafana-kiosk.windows.amd64.exe -c config.yaml
```

config.yaml:

```yaml
general:
  kiosk-mode: full
  autofit: false

target:
  login-method: local
  username: *removed*
  password: *removed*
  playlist: false
  URL: *removed*
```

I don't know how to get the display setting working for Windows systems. Anyone an idea or suggestion how to get this working on 2 monitors on Windows?
