### ISSUE TITLE
Top bar appears after a few hours in full screen kiosk mode

### ISSUE THREAD

**Issue by abctaylor** [grafana/grafana-kiosk#134]
Has anyone seen this behaviour? Initially it starts perfectly:

![image](https://github.com/grafana/grafana-kiosk/assets/30197206/c0311b81-87b0-416c-9bfc-7752ff5517f9)

After some time (typically overnight) the top bar appears:

![image](https://github.com/grafana/grafana-kiosk/assets/30197206/505d85a4-c2b0-4243-ba9c-439572c79959)

Pi 5 Bookworm.

config file:
```
general:
  kiosk-mode: full
  autofit: true
  lxde: true
  lxde-home: /home/l-admin
  scale-factor: 1.0

target:
  login-method: local
  username: xxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxx
  playlist: true
  URL: https://grafana.core.example.net/playlists/play/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx?kiosk&autofitpanels
```
