### ISSUE TITLE
Unable to find application file

### ISSUE THREAD

**Issue by llamafilm** [grafana/grafana-kiosk#159]
I'm running grafana-kiosk on a Raspberry Pi to display a playlist, authenticated with Grafana Cloud service account token.  Every few hours, it shows this screen and needs be restarted.  Clicking the reload button fixes it, but ideally I want this to run unattended.

![Image](https://github.com/user-attachments/assets/8b2583e1-a38f-45c1-85f1-a21ec6da7796)

My config
```yaml
general:
  kiosk-mode: full
target:
  URL: https://xxxxxx.grafana.net/playlists/play/ee9ndvno6u2v4a
  login-method: apikey
  playlist: true
apikey:
  apikey: xxxxx
```

Version 1.0.8
