### ISSUE TITLE
Rasberry Pi 4 Model b won't play/change dashboards

### ISSUE THREAD

**Issue by MightyTitan** [grafana/grafana-kiosk#62]
My Playlist is stuck on the first screen. Below is my config. It logs in properly and shows the first dashboard but it never moves on to the next one.
```
general:
  kiosk-mode: tv
  autofit: true
  lxde: true
  lxde-home: /home/pi

target:
  login-method: local
  username: ****
  password: ***

  playlist: true
  URL: https://*****:3000/d/UcQvlA_Wz
  ignore-certificate-errors: true

goauth:
  auto-login: false
  fieldname-username: username
  fieldname-password: password
```
