### ISSUE TITLE
Not pressing "Log in" for local auth

### ISSUE THREAD

**Issue by David-Igou** [grafana/grafana-kiosk#69]
What I expect to happen: I run `/usr/bin/grafana-kiosk -c /home/pi/grafana-kiosk/grafana-kiosk-config.yaml` and grafana-kiosk opens chromium and logs into my instance of grafana.

What happens: Chromium loads as fullscreen as expected, it loads my grafana login page, and then enters the login and password. But it **does not** log in

System: Raspberry Pi Zero 1.1 running latest Raspberry Pi OS Lite, Openbox
Grafana version: grafana/grafana:8.3.4 - deployed via kube-prometheus
config:

```
general:
  kiosk-mode: full
  autofit: true
  lxde: false

target:
  login-method: local
  username: mygrafanaadmin
  password: changeme
  playlist: false
  URL: https://user:password@grafana.myroute
  ignore-certificate-errors: false
  ```

My instance of grafana is behind a basic htpasswd ingress + it does local login. Not sure if that's relevant, but I've recreated this issue with and without it.

Let me know any other information I can provide
