### ISSUE TITLE
Local Login Fail

### ISSUE THREAD

**Issue by flistonfr** [grafana/grafana-kiosk#78]
Hello! 

I get 'Playlist not found' or "Dashboard not found" error on webpage.
The main reason is that since I update grafana to version 9.0.X grafana-kiosk local login is broken. 

Someone can help me with this?

Thanks!

**Comment by ian-zunderdorp** [comment]
We're using grafana-kiosk on grafana v9.0.6 and after updating chromium on the raspberry pi, it is working correctly with local login.

**Comment by flistonfr** [comment]
> We're using grafana-kiosk on grafana v9.0.6 and after updating chromium on the raspberry pi, it is working correctly with local login.

I have `Chromium 104.0.5112.79 built on Debian 11.4, running on Debian 11.4` but no success.

What version of Chromium are you running?

**Comment by ian-zunderdorp** [comment]
Chromium 92.something

**Comment by ian-zunderdorp** [comment]
Just tested it on another raspberry pi I'm configuring, which is running Chromium 101 and that's working as well.

**Comment by flistonfr** [comment]
Can you show me some config example?

I tried:

One line...

`/usr/bin/grafana-kiosk -URL=http://xxx:3000/playlists/play/pRPQqqenk -login-method=local -username=xx -password=xxx -playlists=true -kiosk-mode=tv
`
Config file...

`/usr/bin/grafana-kiosk -c /path/.config/grafana-kiosk/config.yml`

```
general:
        kiosk-mode: tv
        autofit: true
        lxde: true
        lxde-home: /home/user

target:
    login-method: local
    username: xxx
    password: xxx
    playlists: true
    URL: http://xxx:3000/playlists/play/pRPQqqenk
    ignore-certificate-errors: true
```

Output...

![IMG_4799](https://user-images.githubusercontent.com/94003074/185206355-db90ac05-d7ef-4c7d-ae44-1e3c0dc81b2e.jpg)
![IMG_4800](https://user-images.githubusercontent.com/94003074/185206554-ad5fd1ed-097f-4bd5-931c-0e47146049df.jpg)

**Comment by ian-zunderdorp** [comment]
The configuration file we're using:
```yaml
general:
  kiosk-mode: full
  autofit: true
target:
  URL: https://<host>/d/ha6GGMAWz/applicatie-overview?or>
  username: <email>
  password: <password>
  login-method: local
```

That URL is the full URL that we get when we open a specific dashboard in the browser. We used to use a playlist link as well like you linked before, but currently prefer a single dashboard.
